const projects = [
    {
    id: "kraft-packaging",
    title: "Kraft Packaging",
    category: "packaging",
    categoryName: "Packaging Design",
    client: "Client Project",
    year: "2026",
    type: "Packaging Design",
    role: "Graphic Designer & Prepress",
    url: "kraft-packaging.html",
    hero: "images/packaging/kraft-packaging-design.jpg"
},
    {
        id: "shawarma-tent-prepress",
        title: "Shawarma Tent Prepress",
        category: "prepress",
        categoryName: "Prepress",
        client: "Commercial Project",
        year: "2026",
        type: "Large Format Prepress",
        role: "Prepress Designer",
        url: "shawarma-tent-prepress.html",
        hero: "images/prepress-1/shawarma-tent-final-print.jpg"
    },
    {
    id: "tent-production-logo",
    title: "Tent Production Logo",
    category: "logo",
    categoryName: "Logo Design",
    client: "Private Client",
    year: "2026",
    type: "Logo Design",
    role: "Graphic Designer",
    url: "tent-production-logo.html",
    hero: "images/tent-production-logo/tent-logo-design.jpg"
},
    {
    id: "tent-lettering",
    title: "Tent Lettering",
    category: "prepress",
    categoryName: "Prepress",
    client: "Client Project",
    year: "2026",
    type: "Tent Graphics",
    role: "Prepress Designer",
    url: "tent-prepress.html",
    hero: "images/prepress-2/tent-lettering-final.jpg"
},
 {
    id: "sticker-sheet-prepress",
    title: "Sticker Sheet — Prepress",
    category: "prepress",
    categoryName: "Prepress",
    client: "Client Project",
    year: "2026",
    type: "Sticker Prepress",
    role: "Prepress Designer",
    url: "sticker-sheet-prepress.html",
    hero: "images/prepress-3/sticker-sheet.jpg"
},
    {
    id: "gift-card-prepress",
    title: "Gift Card",
    category: "prepress",
    categoryName: "Prepress",
    client: "Client Project",
    year: "2026",
    type: "Gift Card Prepress",
    role: "Prepress Designer",
    url: "gift-card-prepress.html",
    hero: "images/prepress-4/gift-card-final-front.jpg"
},
    {
    id: "oro-professional",
    title: "ORO Professional",
    category: "logo",
    categoryName: "Logo Design",
    client: "ORO Professional",
    year: "2026",
    type: "Logo Design",
    role: "Graphic Designer",
    url: "oro-professional.html",
    hero: "images/logo-ORO/oro-professional-logo.jpg"
},
    {
id: "retro-envelope-design",
title: "Retro Envelope Design",
category: "graphic",
categoryName: "Graphic Design",
client: "Client Project",
year: "2026",
type: "Envelope Design",
role: "Graphic Designer",
url: "retro-envelope-design.html",
hero: "images/retro-envelope/retro-envelope-design1.jpg"
},  
];
